
// Expenses
export const LOAD_OVERVIEW = 'LOAD_OVERVIEW'
export const LOAD_OVERVIEW_SUCCESS = 'LOAD_OVERVIEW_SUCCESS'
export const LOAD_OVERVIEW_ERROR = 'LOAD_OVERVIEW_ERROR'

export const LOAD_EXPENSES = 'LOAD_EXPENSES'
export const LOAD_EXPENSES_SUCCESS = 'LOAD_EXPENSES_SUCCESS'
export const LOAD_EXPENSES_ERROR = 'LOAD_EXPENSES_ERROR'

export const DELETE_EXPENSE = 'DELETE_EXPENSE'
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS'
export const DELETE_EXPENSE_ERROR = 'DELETE_EXPENSE_ERROR'


// Categories
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES'
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'
export const LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR'


// Users
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
