
// Expenses
export const LOAD_OVERVIEW = 'LOAD_OVERVIEW'
export const LOAD_OVERVIEW_SUCCESS = 'LOAD_OVERVIEW_SUCCESS'
export const LOAD_OVERVIEW_ERROR = 'LOAD_OVERVIEW_ERROR'

export const LOAD_EXPENSES = 'LOAD_EXPENSES'
export const LOAD_EXPENSES_SUCCESS = 'LOAD_EXPENSES_SUCCESS'
export const LOAD_EXPENSES_ERROR = 'LOAD_EXPENSES_ERROR'

export const LOAD_EXPENSE = 'LOAD_EXPENSE'
export const LOAD_EXPENSE_SUCCESS = 'LOAD_EXPENSE_SUCCESS'
export const LOAD_EXPENSE_ERROR = 'LOAD_EXPENSE_ERROR'

export const DELETE_EXPENSE = 'DELETE_EXPENSE'
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS'
export const DELETE_EXPENSE_ERROR = 'DELETE_EXPENSE_ERROR'

export const UPDATE_EXPENSE = 'UPDATE_EXPENSE'
export const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS'
export const UPDATE_EXPENSE_ERROR = 'UPDATE_EXPENSE_ERROR'

export const ADD_EXPENSE = 'ADD_EXPENSE'
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS'
export const ADD_EXPENSE_ERROR = 'ADD_EXPENSE_ERROR'

// Categories
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES'
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'
export const LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR'

// Users
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
